model:
  base_learning_rate: 4.5e-6
  target: ldm.models.x_autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    lossconfig:
      target: ldm.modules.losses.x_contperceptual.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 3
      resolution: 128 
      in_channels: 1
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0


data:
  target: x_main.DataModuleFromConfig
  params:
    batch_size: 12
    f_name: "../sc_training.h5ad"
    frac: 0.2

lightning:
  trainer:
    benchmark: True
    accumulate_grad_batches: 2
